services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "${APP_PORT}:8000"
    command: "uvicorn --factory application.api.main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ../sciarticle_task/:/sciarticle_task/
    networks:
      - backend

networks:
  backend:
    driver: bridge