@startuml
autonumber
title Post message

actor user as "User"
participant api as "API"
participant mediator as "Mediator"
participant command_handler as "CommandHandler"
participant event_handler as "EventHandler"
participant consumer as "Consumer" #LightGreen
participant broker as "MessageBroker" #Cyan
participant websocket_manager as "WebsocketManager"
participant websocket as "Websocket"

user -> api ++: POST message

api -> mediator: PostMessageCommand

mediator -> command_handler

command_handler -> event_handler

event_handler -> broker

api -> user --: HTTP 200: message_id

broker -> consumer

consumer -> event_handler

event_handler -> websocket_manager

websocket_manager -> websocket: message


@enduml