@startuml
autonumber
title Post message

actor user as "User"
participant api as "API"
participant mediator as "Mediator"
participant command_handler as "CommandHandler"
participant event_handler as "EventHandler"
participant broker as "MessageBroker" #cyan
participant websocket_manager as "WebsocketManager"
participant websocket as "Websocket"
actor room as "Room"

user -> api ++: POST /message/

api -> mediator: PostMessageCommand

mediator -> command_handler: message, room_id

command_handler -> event_handler

event_handler -> broker

broker -> event_handler

event_handler -> websocket_manager: message, room_id

websocket_manager -> websocket: message

websocket -> room: message

api -> user --: HTTP 201: CREATED, command_id

@enduml